apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-restore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-restore
  labels:
    app: kafka-restore
spec:
  replicas: 15
  selector:
    matchLabels:
      app: kafka-restore
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /__/metrics
        prometheus.io/port: "8081"
      labels:
        app: kafka-restore
    spec:
      serviceAccountName: kafka-restore
      containers:
        - name: kafka-restore
          image: quay.io/utilitywarehouse/kafka-data-keep:main
          imagePullPolicy: IfNotPresent
          command: ["/kafka-data-keep", "restore"]
          env:
            - name: KAFKA_BROKERS
              value: TBD
            - name: KAFKA_PLAN_TOPIC
              value: pubsub.plan-topic-restore
            - name: KAFKA_CONSUMER_GROUP
              value: pubsub.kafka-restore
            - name: KAFKA_RESTORE_TOPIC_PREFIX
              value: ""
            - name: S3_BUCKET
              value: TBD
            - name: AWS_REGION
              value: eu-west-1
          resources:
            requests:
              cpu: "0"
              memory: "0"
            limits:
              cpu: "4"
              memory: 4Gi
