version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  # Enable specific linters in addition to defaults
  enable:
    - misspell
    - gocritic
    - gocognit # Cognitive complexity is often better than Cyclomatic

    # --- Senior Recommendations ---
    - bodyclose   # HTTP body leaks
    - noctx       # HTTP requests without context
#    - revive      # Replacement for golint
    - gosec       # Security checks
    - errorlint   # Go 1.13+ error wrapping support
    - unconvert   # Remove unnecessary conversions
    - prealloc    # Performance: slice pre-allocation
    - nakedret    # Disallow naked returns in long functions

# Enable formtters explicitly. None is enabled by default
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
