apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-topics-backup
---
apiVersion: apps/v1
# Using a Stateful Set to get permanent PVCs attached
kind: StatefulSet
metadata:
  name: kafka-topics-backup
  labels:
    app: kafka-topics-backup
    app.kubernetes.io/name: kafka-topics-backup
spec:
  # Initialize all pods at the same time, otherwise rebalances will happen each time a pod is started
  podManagementPolicy: Parallel
  replicas: 2
  # Allow all pods to be updated at the same time to minimize the consumer group rebalances
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # It requires the MaxUnavailableStatefulSet feature gate set to true.
      # This is supported since 1.24, and it defaults to true from 1.35
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: kafka-topics-backup
      app.kubernetes.io/name: kafka-topics-backup
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /__/metrics
        prometheus.io/port: "8081"
      labels:
        app: kafka-topics-backup
        app.kubernetes.io/name: kafka-topics-backup
    spec:
      serviceAccountName: kafka-topics-backup
      securityContext:
        # Change ownership to the group created in Dockerfile to be able to write PVCs
        fsGroup: 1000
      containers:
        - name: kafka-topics-backup
          image: quay.io/utilitywarehouse/kafka-data-keep:main
          imagePullPolicy: IfNotPresent
          command: ["/kafka-data-keep", "topics-backup"]
          env:
            - name: GOMEMLIMIT
              value: "3GiB"
            - name: KAFKA_BROKERS
              value: TBD
            # Convenient way of passing the seed brokers in a single DNS SRV record with the service name being "kafka"
            - name: KAFKA_BROKERS_DNS_SRV
              value: ""
            - name: KAFKA_MTLS_AUTH
              value: "false"
            - name: KAFKA_MTLS_CA_CERT_PATH
              value: /certs/ca.crt
            - name: KAFKA_MTLS_CLIENT_CERT_PATH
              value: /certs/tls.crt
            - name: KAFKA_MTLS_CLIENT_KEY_PATH
              value: /certs/tls.key
            - name: KAFKA_GROUP_ID
              value: TBD
            - name: KAFKA_TOPICS_REGEX
              value: .*
            - name: KAFKA_EXCLUDE_TOPICS_REGEX
              value: ""
            - name: S3_BUCKET
              value: TBD
            - name: S3_PREFIX
              value: kafka-topics-backup
            - name: WORKING_DIR
              value: /backup-workdir
            - name: LOG_LEVEL
              value: INFO
            - name: LOG_FORMAT
              value: text
            - name: KGO_LOG_LEVEL
              value: WARN
            - name: METRICS_PORT
              value: "8081"
            - name: ENABLE_PPROF
              value: "false"
            - name: PPROF_PORT
              value: "6060"
          ports:
            - containerPort: 8081
              name: ops
          volumeMounts:
            - mountPath: /backup-workdir
              name: workdir
              readOnly: false
          resources:
            requests:
              cpu: "0"
              memory: "0"
            limits:
              cpu: "4"
              memory: 4Gi
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
