name: go

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # allows the workflow to request an OIDC token for vault auth
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Test
        run: make test
